### ISSUE TITLE
Document existing infrastructure

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-conda-forge-mgmt#31]
```[tasklist]
### Tasks to complete
- [x] [Initial Docusaurus setup + content structure](https://github.com/Quansight-Labs/czi-cf-docs/pull/1)
- [ ] #32
- [ ] #34
```

## Resources

- [PSF infra documentation](https://infra.psf.io/): good example of how to structure the information and audit
- [cabotage](https://github.com/cabotage/cabotage-app) - PSF K8s cluster management app

**Comment by jaimergp** [comment]
Some comments (and ideas based on these comments) we've had on the last sync:

- Declarative Infrastructure as Code approaches are nice because there's an authoritary inventory of the resources.
- If conda-forge's infra can be expressed as Terraform state declarations, awesome, but simply documenting and inventorying the components is a HUGE step.
- Many of the infra tasks at conda-forge are procedural (list of actions to take to achieve a state), but they could benefit from being declarative (expressing the state we want to achieve, have _magic_ ✨ figure out what actions need to be done). This is the whole idea behind Terraform, so if we can implement it with it, so be it, but if we can't, many of the design principles can / should be applied to CF's automation.

**Comment by trallard** [comment]
Current docs at https://conda-forge.org/docs/maintainer/infrastructure/

**Comment by jaimergp** [comment]
@zklaus to integrate efforts in cf-infra-docs with current docs (^).

**Comment by jaimergp** [comment]
With the current docs at cf-infra-docs I'm quite ok with marking this as done and then iterating in conda-forge.org as part of the PR review process. @zklaus will be tackling that in #55
